version: 2.1

orbs:
  node: circleci/node@6.1.0
  go: circleci/go@1.11.0

jobs:
  build-backend:
    executor: go/default
    steps:
      - checkout
      - run:
          name: Tidy Go modules
          command: go mod tidy
      - go/install-deps:
          cache-path: ~/go/pkg/mod
      - run:
          name: Build backend
          command: go run build.go build

  build-frontend:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install frontend dependencies with Yarn
          command: yarn install --immutable
      - run:
          name: Build frontend
          command: yarn build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-backend
      - build-frontend
