version: 2.1

executors:
  python-cimg-executor:
    docker:
      - image: cimg/python:3.9

jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install Go dependencies
          command: go mod tidy
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg/mod
      - run:
          name: Build Go backend
          command: go build -o grafana-server ./cmd/grafana
      - run:
          name: Install Yarn dependencies
          command: yarn install --immutable
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build Yarn frontend
          command: yarn build
      - run:
          name: Build Docker image
          command: docker build -t gcr.io/coderabbit/grafana:latest .

workflows:
  version: 2
  build-image:
    jobs:
      - build:
          name: image-build-grafana
          filters:
            branches:
              only:
                - coderabbit_micro_frontend
                - pull/requests
