version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.22.6
    working_directory: ~/go/src/github.com/coderabbitai/grafana

  node-executor:
    docker:
      - image: cimg/node:22.7.0
    working_directory: ~/frontend

jobs:
  build-backend:
    executor: go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
            - go-mod-cache-
      - run:
          name: Install Go dependencies
          command: go mod download
      - run:
          name: Go mod tidy
          command: go mod tidy
      - save_cache:
          paths:
            - ~/go/pkg/mod
          key: go-mod-cache-{{ checksum "go.sum" }}
      - run:
          name: Run Grafana backend
          command: go run ./pkg/cmd/grafana/main.go

  build-frontend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run:
          name: Install frontend dependencies
          command: yarn install --immutable
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build frontend
          command: yarn run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-backend
      - build-frontend
