version: 2.1

executors:
  python-cimg-executor:
    docker:
      - image: cimg/python:3.9

jobs:
  build-push-add-tag:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install Go dependencies
          command: go mod tidy
      - run:
          name: Build Go backend
          command: go build -o grafana-server ./cmd/grafana
      - run:
          name: Install Yarn dependencies
          command: yarn install --immutable
      - run:
          name: Build Yarn frontend
          command: yarn build
      - run:
          name: Build Docker image
          command: docker build -t gcr.io/coderabbit/grafana:latest .
      - run:
          name: Push Docker image
          command: docker push gcr.io/coderabbit/grafana:latest
      - run:
          name: Deploy to Cloud Run
          command: gcloud run deploy grafana --image gcr.io/coderabbit/grafana:latest --region us-central1 --allow-unauthenticated --vpc-connector=coderabbitai-dev-cr

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-push-add-tag:
          name: image-build-grafana
          filters:
            branches:
              only:
                - coderabbit_micro_frontend