version: 2.1

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.18
    working_directory: ~/go/src/github.com/coderabbitai/grafana

  node-executor:
    docker:
      - image: circleci/node:16
    working_directory: ~/frontend

jobs:
  build-backend:
    executor: go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-cache-{{ checksum "go.sum" }}
            - go-mod-cache-
      - run:
          name: Install Go dependencies
          command: go mod download
      - save_cache:
          paths:
            - ~/go/pkg/mod
          key: go-mod-cache-{{ checksum "go.sum" }}
      - run:
          name: Build backend
          command: go build -o bin/backend ./...

  build-frontend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run:
          name: Install frontend dependencies
          command: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Build frontend
          command: yarn build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-backend
      - build-frontend
