name: Deploy Grafana Server Cloud Run

on:
  push:
    branches:
      - fluxninja_micro_frontends
    paths:
      - "/**"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLECLOUDSA }}

      - uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ github.workflow }}-

      - run: gcloud auth configure-docker

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gcr.io/coderabbit/grafana:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-contexts: |
            mono=${{ github.workspace }}

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Deploy to Cloud Run
        run: gcloud run deploy grafana --image gcr.io/coderabbit/grafana:latest --region us-central1 --allow-unauthenticated --vpc-connector=coderabbitai-dev-cr
