name: Run commands when issues are opened
on:
  issues:
    types: [opened]
concurrency:
  group: issue-opened-${{ github.event.issue.number }}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      # give issue-openers a chance to add labels after submit
      - name: Sleep for 2 minutes
        run: sleep 2m
        shell: bash
      - name: Run Commands
        uses: ./actions/commands
        with:
          metricsWriteAPIKey: ${{secrets.GRAFANA_MISC_STATS_API_KEY}}
<<<<<<<< HEAD:.github/workflows/issue-opened.yml
          token: ${{secrets.ISSUE_COMMANDS_TOKEN}}
          configPath: "issue-opened"
|||||||| 78f0340031:.github/workflows/commands.yml
          token: ${{secrets.GH_BOT_ACCESS_TOKEN}}
          configPath: commands
========
          token: ${{secrets.ISSUE_COMMANDS_TOKEN}}
          configPath: commands
>>>>>>>> v10.1.1:.github/workflows/commands.yml
