name: Deploy test trigger for grafana

on:
  push:
    branches:
      - test/grafana
    paths:
      - "/**"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLECLOUDSA_PROD }}

      - uses: docker/setup-buildx-action@v3



      - run: gcloud auth configure-docker


      
